# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Flow-Launcher.Flow-Launcher
PackageVersion: 1.19.2
InstallerLocale: en-US
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ReleaseDate: 2024-09-24
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Flow-Launcher/Flow.Launcher/releases/download/v1.19.2/Flow-Launcher-Setup.exe
  InstallerSha256: E3C0811D7241D3BAE01E405FC5077AD35BAA0F17A5B1F0BC22A6CE900457FC20
ManifestType: installer
ManifestVersion: 1.5.0
